2023-09-27 12:33:33,252 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STARTED
2023-09-27 12:33:33,252 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_READY2CONNECT
2023-09-27 12:33:33,271 - Gdb - ERROR - Failed to config GDB (gdb process has already finished with return code: 127)!
2023-09-27 12:33:33,271 - Debug Adapter (main) - ERROR - gdb process has already finished with return code: 127
Traceback (most recent call last):
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/gdb.py", line 189, in _mi_cmd_run
    r = self._gdbmi.get_gdb_response(timeout_sec=0, raise_error_on_timeout=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/pygdbmi/gdbcontroller.py", line 269, in get_gdb_response
    self.verify_valid_gdb_subprocess()
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/pygdbmi/gdbcontroller.py", line 175, in verify_valid_gdb_subprocess
    raise NoGdbProcessError(
pygdbmi.gdbcontroller.NoGdbProcessError: gdb process has already finished with return code: 127

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ninh/.vscode/extensions/espressif.esp-idf-extension-1.6.4/esp_debug_adapter/debug_adapter/command_processor.py", line 52, in __call__
    on_request(protocol_message)
  File "/home/ninh/.vscode/extensions/espressif.esp-idf-extension-1.6.4/esp_debug_adapter/debug_adapter/command_processor.py", line 75, in on_initialize_request
    raise e
  File "/home/ninh/.vscode/extensions/espressif.esp-idf-extension-1.6.4/esp_debug_adapter/debug_adapter/command_processor.py", line 70, in on_initialize_request
    self.da.adapter_init()
  File "/home/ninh/.vscode/extensions/espressif.esp-idf-extension-1.6.4/esp_debug_adapter/debug_adapter/debug_adapter.py", line 329, in adapter_init
    raise e
  File "/home/ninh/.vscode/extensions/espressif.esp-idf-extension-1.6.4/esp_debug_adapter/debug_adapter/debug_adapter.py", line 325, in adapter_init
    self.start_gdb()
  File "/home/ninh/.vscode/extensions/espressif.esp-idf-extension-1.6.4/esp_debug_adapter/debug_adapter/debug_adapter.py", line 678, in start_gdb
    raise e
  File "/home/ninh/.vscode/extensions/espressif.esp-idf-extension-1.6.4/esp_debug_adapter/debug_adapter/debug_adapter.py", line 652, in start_gdb
    self._gdb = dbg.create_gdb(chip_name=self.args.device_name,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/__init__.py", line 75, in create_gdb
    return gdb_cls(**gdb_init_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/hw_specific/esp.py", line 343, in __init__
    super(GdbEsp32c3, self).__init__(gdb_path=gdb_path, remote_target=remote_target,
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/hw_specific/esp.py", line 246, in __init__
    GdbRiscv.__init__(self, gdb_path=gdb_path, remote_target=remote_target,
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/hw_specific/riscv.py", line 28, in __init__
    super(GdbRiscv, self).__init__(gdb_path=gdb_path, remote_target=remote_target, extended_remote_mode=extended_remote_mode,
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/gdb.py", line 87, in __init__
    raise e
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/gdb.py", line 66, in __init__
    self.gdb_set("mi-async", "on")
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/gdb.py", line 423, in gdb_set
    res, _ = self._mi_cmd_run("-gdb-set %s %s" % (var, val))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/gdb.py", line 193, in _mi_cmd_run
    verify_valid_gdb_subprocess(self._gdbmi.gdb_process)
  File "/home/ninh/.espressif/python_env/idf4.4_py3.11_env/lib/python3.11/site-packages/esp_debug_backend/utils.py", line 23, in verify_valid_gdb_subprocess
    raise NoGdbProcessError(
esp_debug_backend.defs.NoGdbProcessError: gdb process has already finished with return code: 127
2023-09-27 12:33:33,279 - Debug Adapter (main) - CRITICAL - Debug adapter -> Extension: DEBUG_ADAPTER_STOPPED
